### ISSUE TITLE
Quieres ser miembro de la organización en Github?

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/Organizacion#1]
Hola!

Si estas interesado en ser [miembro de la organización en GIthub](https://github.com/orgs/OSWeekends/people), solo tienes que responder a este issue con tu ID de SLACK, para poder validar tu identidad.

Si aún no estas en Slack, [¿A que esperas?](http://invitations-osweekends.herokuapp.com/)

La idea de organizar a nuestros miembros aquí sobretodo nos permite organizarnos por grupos de interes (big data, iot, front, back, bases de datos...) de cara a próximos y actuales proyectos.

**Más info**
- [Publicizing or hiding organization membership](https://help.github.com/articles/publicizing-or-hiding-organization-membership/)
- [Repository permission levels for an organization](https://help.github.com/articles/repository-permission-levels-for-an-organization/)

**Comment by sjuanman** [comment]
Hola, yo estoy interesado. mi id de slack es juanma

**Comment by ymdx** [comment]
Yo respondo con un hash 256 con mi nombre de usuario, gracias! -> 5a5c5f10323bf47e8fdc124db13c72902d7bfdebcf261517ac941a03074271d4

**Comment by xDae** [comment]
Aqui uno más que se sube al carro!

id de slack: xdae

**Comment by soyjuanmacias** [comment]
Me apunto al carro!! Yeahh
User de slack: juanmacias
👍

**Comment by elemikelo** [comment]
{
  "id": "luismi"
}
🤘🏽

**Comment by Jorgeural** [comment]
@jorgeural aquí ;)

**Comment by Adolfo2010** [comment]
Hola, en el canal de Slack soy asolero
¡¡Gracias por la iniciativa!!

**Comment by Monzonprog** [comment]
En lo que el tiempo me permita ayudaré, cuenta con mi hacha!!! 

Jmonzon en slack!

**Comment by valenber** [comment]
valenber

**Comment by UlisesGascon** [comment]
Hola a todos! Ya habéis sido invitados.. recordad que tenéis que aceptar la invitación que os llegará al email, o podéis pinchar directamente [aquí](https://github.com/OSWeekends/invitations).

Por otro lado... Por defecto las organizaciones no se muestran públicamente en los perfiles de los usuarios, así que si queréis mostrar con orgullo que sois miembros de OSW, Solo tenéis que seguir [estos pasos](https://help.github.com/articles/publicizing-or-hiding-organization-membership/)

**Comment by kidandcat** [comment]
Me apunto! jairo

**Comment by letzgar** [comment]
Hola, me gustaria apuntarme!!
mi id de Slack es: letzgar

**Comment by Sediug** [comment]
Buenas tardes. Sebastiancbvz en slack :+1:

**Comment by ValKiriann** [comment]
Hola! soy Ana Enríquez en slack

**Comment by redlim** [comment]
Hola... 
Cuenta conmigo.. intentaré ayudar en lo que pueda
Mi usuario es @will

**Comment by will** [comment]
No, mi usuario es @will, y tambien mi espanol es muy malo.

**Comment by LeylaVieira** [comment]
Hola! yo también quiero apuntarme. Mi user en slack es @leyla :smile:

**Comment by UlisesGascon** [comment]
Hola a todos! Ya habéis sido invitados.. recordad que tenéis que aceptar la invitación que os llegará al email, o podéis pinchar directamente [aquí](https://github.com/OSWeekends/invitations).

Por otro lado... Por defecto las organizaciones no se muestran públicamente en los perfiles de los usuarios, así que si queréis mostrar con orgullo que sois miembros de OSW, Solo tenéis que seguir [estos pasos](https://help.github.com/articles/publicizing-or-hiding-organization-membership/)

**Comment by txesus** [comment]
¡Hola! 
En el canal de Slack soy @jesusesteban
En Github: @txesus

**Comment by Vickysolo** [comment]
Hola!

En slack soy vickysolo

**Comment by inigojorcano** [comment]
Hola!!
En slack soy @Iñigo
En github soy @inigojorcano

**Comment by vmrodriguez95** [comment]
En slack soy @Víctor

**Comment by k0sasp** [comment]
Hola

En slack soy soy @David

**Comment by felixrigau** [comment]
Hola, soy @felixrigau en slack

**Comment by Tokytome** [comment]
Hola! Soy **@Tokytome** en slack  ^^

**Comment by bytelovers** [comment]
Hola! Yo soy @alfredo en slack 😸 😸 😸 😸

**Comment by trigoporres** [comment]
Buenas tardes¡¡¡ En slack soy @santiago

**Comment by NuriaHill** [comment]
Hola. si. @nuria

**Comment by laubolgo** [comment]
En Slack Laura Bolaños
En Github laubolgo

**Comment by javimostoles** [comment]
¡Hola!

En Slack @javimostoles
En Github: @javimostoles

**Comment by ismaelocaramelo** [comment]
Hola!

Slack: @ismaelo

**Comment by denisse-dev** [comment]
Hola, soy @andrea en Slack. 😄

**Comment by jonasync** [comment]
Muy buenas @jonasync en Slack!

Un saludo!

**Comment by jfpernas** [comment]
Hola, soy @jfpernas en Slack!

Un saludo.

**Comment by Andrea** [comment]
Hi I am @andrea (on github), please don't use my handle here as I become notified of mentions

**Comment by vilvadot** [comment]
Hola, soy @vilva en Slack!

Gracias.

**Comment by Skattspa** [comment]
Hola! 
Me gustaría entrar. Soy @JuanMa en Slack. 
Gracias! :)

**Comment by Sebastian217** [comment]
Hola
Sebastian217
Gracias

**Comment by dimiste** [comment]
Me gustaría participar en vuestro grupo, mi id en slack es: dimiste
gracias

**Comment by laubolgo** [comment]
Hola! A la distancia ahora: soy @laubolgo
