### ISSUE TITLE
Proponer una charla/taller!

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/Organizacion#2]
Hola!

Responde a este issue para proponer una charla, ya sea temática, ponente, etc...

No es necesario definir un ponente aunque estaría genial, en cuanto a la temática estamos muy abiertos, y no solo a temas de desarrollo. Aunque si nos interesaría en la medida de lo posible que fueran temáticas relacionadas con el Open Source y tecnologías libres.

¡Incluso puedes proponerte a ti mismo para dar una charla o taller!

**Comment by ardiadrianadri** [comment]
Hola @UlisesGascon 

Me propongo a mismo para dar un taller de introducción a Angular. Necesitaría un total de 4 horas y el nivel sería de total novato. Vamos, para que gente que nunca a tocado la suite y quiere empezar a tomar contacto.

Ya me decís si os cuadra.

**Comment by UlisesGascon** [comment]
Hola @ardiadrianadri ! 

Me parece una buena idea, podríamos partirlo en dos sesiones de 2h?

Si no.. podemos buscar un hueco en el Community Day como taller :-)

**Comment by ardiadrianadri** [comment]
Ambas soluciones me parecen geniales. Te dejo que lo decidas tu

**Comment by alexrm1x** [comment]
¡Hola @UlisesGascon y todos!
Yo puedo ayudar con una charla de Mautic (open source marketing automation) que valdría con 1,5 horas y si lo queréis en formato taller para implementarlo con un Wordpress pues 4h.
Alejandro.-

**Comment by UlisesGascon** [comment]
Genial @alexrm1x! Si te parece nos coordinamos por Slack para encontrar una fecha adecuada, me parece una charla muy interesante!
