### ISSUE TITLE
Liando gente para OSW

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/Organizacion#4]
En los últimos tiempos se esta convirtiendo en una costumbre popular en el ecosistema... liar a alguien para dar una charla/taller en OSW... asi que para hacerlo más facil y centralizar, hemos decidido crear este issue.

**:exclamation:Solo dinos a quien quieres liar (nombre, user, twitter..) y que tipo de charla/taller te gustaría que diera y que es lo que hace a esa persona tan especial.**

Nosotros nos encargamos de conseguirlo :sunglasses:

![img](https://orig00.deviantart.net/25d3/f/2013/086/3/e/sky_is_the_limit_gif_by_marylaponymorada-d5ziotg.gif)

**Comment by KoolTheba** [comment]
We just simply Love iT!
